name: Build and Upload JAR

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: traffic-sim-jar
          path: target/*.jar